services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    container_name: api-gateway-nuzha
    restart: always
    env_file:
      - .env
    ports:
      - '4098:4098'
    depends_on:
      - rabbitmq

  user-service:
    build:
      context: .
      dockerfile: ./apps/user-service/Dockerfile
      target: development
    command: yarn start:dev user-service
    restart: always
    env_file:
      - .env
    depends_on:
      - user-db
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4011:4011'

  real-time-chat:
    build:
      context: .
      dockerfile: ./apps/real-time-chat-service/Dockerfile
      target: development
    command: yarn start:dev real-time-chat-service
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4029:4029'

  page-builder:
    build:
      context: .
      dockerfile: ./apps/page-builder/Dockerfile
      target: development
    command: yarn start:dev user-service
    restart: always
    env_file:
      - .env
    depends_on:
      - page-builder-db
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '4022:4022'

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-nuzha
    restart: always
    ports:
      - '5674:5674'
      - '15674:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
      - RABBITMQ_NODE_PORT=5674

  user-db:
    container_name: user-db-nuzha
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user-db
      - PGPORT=5433
    volumes:
      - user-db-data:/var/lib/postgresql/data
    ports:
      - '5433:5433'

  page-builder-db:
    container_name: page-builder-db-nuzha
    image: postgres:16.0
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=page-builder-db
      - PGPORT=5487
    volumes:
      - page-builder-db-data:/var/lib/postgresql/data
    ports:
      - '5487:5487'

volumes:
  user-db-data:
  page-builder-db-data:
